<?php
/**
 * PHPStorm stub file for Couchbase.
 *
 * @link http://docs.couchbase.com/sdk-api/couchbase-php-client-2.0.7/index.html
 * Maintiner: wayne530@gmail.com
 *
 * @link https://github.com/wayne530/phpstorm-couchbase-stub
 */

/**
 *
 */
const COUCHBASE_AUTH_CONTINUE = 0x01;
const COUCHBASE_AUTH_ERROR = 0x02;
const COUCHBASE_BAD_ENVIRONMENT = 0x24;
const COUCHBASE_BUCKET_ENOENT = 0x19;
const COUCHBASE_CLIENT_ENOMEM = 0x1a;
const COUCHBASE_CLIENT_ETMPFAIL = 0x1b;
const COUCHBASE_CONNECT_ERROR = 0x18;
const COUCHBASE_DELTA_BADVAL = 0x03;
const COUCHBASE_DLOPEN_FAILED = 0x0e;
const COUCHBASE_DLSYM_FAILED = 0x0f;
const COUCHBASE_DUPLICATE_COMMANDS = 0x22;
const COUCHBASE_DURABILITY_ETOOMANY = 0x21;
const COUCHBASE_E2BIG = 0x04;
const COUCHBASE_EBADHANDLE = 0x1c;
const COUCHBASE_EBUSY = 0x05;
const COUCHBASE_EINTERNAL = 0x06;
const COUCHBASE_EINVAL = 0x07;
const COUCHBASE_ENOMEM = 0x08;
const COUCHBASE_ERANGE = 0x09;
const COUCHBASE_ERROR = 0x0a;
const COUCHBASE_ETIMEDOUT = 0x17;
const COUCHBASE_ETMPFAIL = 0x0b;
const COUCHBASE_INVALID_CHAR = 0x20;
const COUCHBASE_INVALID_HOST_FORMAT = 0x1f;
const COUCHBASE_KEY_EEXISTS = 0x0c;
const COUCHBASE_KEY_ENOENT = 0x0d;
const COUCHBASE_NETWORK_ERROR = 0x10;
const COUCHBASE_NOT_MY_VBUCKET = 0x11;
const COUCHBASE_NOT_STORED = 0x12;
const COUCHBASE_NOT_SUPPORTED = 0x13;
const COUCHBASE_NO_MATCHING_SERVER = 0x23;
const COUCHBASE_PLUGIN_VERSION_MISMATCH = 0x1e;
const COUCHBASE_PROTOCOL_ERROR = 0x16;
const COUCHBASE_SERVER_BUG = 0x1d;
const COUCHBASE_SUCCESS = 0x00;
const COUCHBASE_UNKNOWN_COMMAND = 0x14;
const COUCHBASE_UNKNOWN_HOST = 0x15;
const COUCHBASE_VALUE_F_JSON = 0x01;
