<?php
/**
 * PHPStorm stub file for Ming (flash) constants.
 *
 * @link http://php.net/manual/en/ming.constants.php
 */

/**
 * @link  http://php.net/manual/en/ming.constants.php
 */
const MING_NEW = 1;
const MING_ZLIB = 1;
const SWFACTION_DATA = 256;
const SWFACTION_ENTERFRAME = 2;
const SWFACTION_KEYDOWN = 64;
const SWFACTION_KEYUP = 128;
const SWFACTION_MOUSEDOWN = 16;
const SWFACTION_MOUSEMOVE = 8;
const SWFACTION_MOUSEUP = 32;
const SWFACTION_ONLOAD = 1;
const SWFACTION_UNLOAD = 4;
const SWFBUTTON_DOWN = 4;
const SWFBUTTON_DRAGOUT = 272;
const SWFBUTTON_DRAGOVER = 160;
const SWFBUTTON_HIT = 8;
const SWFBUTTON_MOUSEDOWN = 4;
const SWFBUTTON_MOUSEOUT = 2;
const SWFBUTTON_MOUSEOVER = 1;
const SWFBUTTON_MOUSEUP = 8;
const SWFBUTTON_MOUSEUPOUTSIDE = 64;
const SWFBUTTON_OVER = 2;
const SWFBUTTON_UP = 1;
const SWFFILL_CLIPPED_BITMAP = 65;
const SWFFILL_LINEAR_GRADIENT = 16;
const SWFFILL_RADIAL_GRADIENT = 18;
const SWFFILL_TILED_BITMAP = 64;
const SWFTEXTFIELD_ALIGN_CENTER = 2;
const SWFTEXTFIELD_ALIGN_JUSTIFY = 3;
const SWFTEXTFIELD_ALIGN_LEFT = 0;
const SWFTEXTFIELD_ALIGN_RIGHT = 1;
const SWFTEXTFIELD_AUTOSIZE = 16384;
const SWFTEXTFIELD_DRAWBOX = 2048;
const SWFTEXTFIELD_HASLENGTH = 2;
const SWFTEXTFIELD_HTML = 512;
const SWFTEXTFIELD_MULTILINE = 32;
const SWFTEXTFIELD_NOEDIT = 8;
const SWFTEXTFIELD_NOSELECT = 4096;
const SWFTEXTFIELD_PASSWORD = 16;
const SWFTEXTFIELD_USEFONT = 256;
const SWFTEXTFIELD_WORDWRAP = 64;
const SWF_SOUND_11KHZ = 4;
const SWF_SOUND_16BITS = 2;
const SWF_SOUND_22KHZ = 8;
const SWF_SOUND_44KHZ = 12;
const SWF_SOUND_5KHZ = 0;
const SWF_SOUND_8BITS = 0;
const SWF_SOUND_ADPCM_COMPRESSED = 16;
const SWF_SOUND_MONO = 0;
const SWF_SOUND_MP3_COMPRESSED = 32;
const SWF_SOUND_NELLY_COMPRESSED = 96;
const SWF_SOUND_NOT_COMPRESSED = 0;
const SWF_SOUND_NOT_COMPRESSED_LE = 48;
const SWF_SOUND_STEREO = 1;
