<?php
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_CLEAN = 2;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_CLEANABLE = 16;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_CONT = 0;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_DISABLED = 8192;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_FINAL = 8;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_FLUSH = 4;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_FLUSHABLE = 32;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_REMOVABLE = 64;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_START = 1;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_STARTED = 4096;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_STDFLAGS = 112;
/** @link http://php.net/manual/en/outcontrol.constants.php */
const PHP_OUTPUT_HANDLER_WRITE = 0;
