<?php
/**
 * PHPStorm stub file for Zend constants.
 */

/**
 *
 */
const JOB_QUEUE_PRIORITY_HIGH = 2;
const JOB_QUEUE_PRIORITY_LOW = 0;
const JOB_QUEUE_PRIORITY_NORMAL = 1;
const JOB_QUEUE_PRIORITY_URGENT = 3;
const JOB_QUEUE_SAVE_COOKIE = 4;
const JOB_QUEUE_SAVE_ENV = 128;
const JOB_QUEUE_SAVE_FILES = 64;
const JOB_QUEUE_SAVE_GET = 2;
const JOB_QUEUE_SAVE_POST = 1;
const JOB_QUEUE_SAVE_RAW_POST = 16;
const JOB_QUEUE_SAVE_SERVER = 32;
const JOB_QUEUE_SAVE_SESSION = 8;
const JOB_QUEUE_STATUS_EXECUTION_FAILED = 7;
const JOB_QUEUE_STATUS_IN_PROCESS = 6;
const JOB_QUEUE_STATUS_LOGICALLY_FAILED = 8;
const JOB_QUEUE_STATUS_SCHEDULED = 4;
const JOB_QUEUE_STATUS_SUCCESS = 1;
const JOB_QUEUE_STATUS_SUSPENDED = 3;
const JOB_QUEUE_STATUS_WAITING = 2;
const JOB_QUEUE_STATUS_WAITING_PREDECESSOR = 5;
