version: '2'
services:
  php:
    image: php:7.3
    volumes:
     - .:/opt/project
  composer:
    restart: 'no'
    image: composer:1.8
    command: install
    working_dir: /opt/project
    volumes:
      - .:/opt/project