<?php
declare(strict_types=1);

const RD_KAFKA_RESP_ERR_THROTTLING_QUOTA_EXCEEDED = 89;
const RD_KAFKA_RESP_ERR_PRODUCER_FENCED = 90;
const RD_KAFKA_RESP_ERR_RESOURCE_NOT_FOUND = 91;
const RD_KAFKA_RESP_ERR_DUPLICATE_RESOURCE = 92;
const RD_KAFKA_RESP_ERR_UNACCEPTABLE_CREDENTIAL = 93;
const RD_KAFKA_RESP_ERR_INCONSISTENT_VOTER_SET = 94;
const RD_KAFKA_RESP_ERR_INVALID_UPDATE_VERSION = 95;
const RD_KAFKA_RESP_ERR_FEATURE_UPDATE_FAILED = 96;
const RD_KAFKA_RESP_ERR_PRINCIPAL_DESERIALIZATION_FAILURE = 97;
const RD_KAFKA_RESP_ERR__ASSIGNMENT_LOST = -142;
const RD_KAFKA_RESP_ERR__NOOP = -141;
const RD_KAFKA_RESP_ERR__AUTO_OFFSET_RESET = -140;
