name: PhpStorm Stubs Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer Install
        run: composer install --ignore-platform-reqs

      - name: Build Docker Container
        run: docker-compose -f docker-compose.yml build >/dev/null

      - name: Run Tests
        run: docker-compose -f docker-compose.yml run php /opt/project/phpstorm-stubs/vendor/bin/phpunit /opt/project/phpstorm-stubs/tests/

      - name: Test Stubs Map
        run: ./tests/check-stub-map

      #- name: run cs fixer
      #  run: composer cs
