name: PhpStorm Stubs Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: '* * 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer Install
        run: composer install --ignore-platform-reqs
        env:
          PHP_VERSION: '8.0'

      - name: Build Docker Container
        run: docker-compose -f docker-compose.yml build >/dev/null
        env:
          PHP_VERSION: '8.0'

      - name: Run Tests
        run: docker-compose -f docker-compose.yml run -e CHECK_LINKS=true php /opt/project/phpstorm-stubs/vendor/bin/phpunit /opt/project/phpstorm-stubs/tests/
        env:
          PHP_VERSION: '8.0'
